### ISSUE TITLE
重复md5 计算

### ISSUE THREAD

**Issue by samuelyao314** [hit9/ketama#1]
alignHash 里直接有 md5 ，是有问题的。这样原先只要算1次，现在需要重复算4次

**Comment by samuelyao314** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/2543265/174766820-0c91e1b2-93e4-4e17-b4b9-b0fa71969a9e.png">

你看原始java 实现。

**Comment by hit9** [comment]
对的。

感谢， 已经修复：https://github.com/hit9/ketama/commit/800d01e315d80e82b3a9c103ffb1c88eed90b072
